#' Country Code Lookup
#'
#' @description
#' These pre-defined country codes are sourced from
#' [ISO 3166 Standards](https://www.iso.org/iso-3166-country-codes.html).
#' See also [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3).
#'
#' @details
#'
#' `country_code` is the 3-letter ISO 3166-1 county code commonly found in the
#' ADSL `COUNTRY` variable.
#' `country_name` is the country long name corresponding to to the 3-letter code.
#' `country_number` is the numeric code corresponding to an alphabetic sorting of
#' the 3-letter codes.
#'
#' To see the entire table in the console, run `print(country_code_lookup)`.
#'
#' @seealso [dose_freq_lookup]
#'
#' @export
#'
#' @keywords metadata
#'
#' @family metadata
#'
#' @examples
#' library(tibble)
#' library(dplyr, warn.conflicts = FALSE)
#' library(lubridate)
#'
#' # Create reference dataset for periods
#' adsl <- tribble( #' adsl <- tribble(
#'   ~USUBJID, ~SEX, ~COUNTRY,
#'   "ST01-01", "F", "AUT",
#'   "ST01-02", "M", "MWI",
#'   "ST01-03", "F", "GBR",
#'   "ST01-04", "M", "CHE",
#'   "ST01-05", "M", "NOR",
#'   "ST01-06", "F", "JPN",
#'   "ST01-07", "F", "USA"
#' )
#'
#' covar <- adsl %>%
#'   derive_vars_merged(
#'     dataset_add = country_code_lookup,
#'     new_vars = exprs(COUNTRYN = country_number, COUNTRYL = country_name),
#'     by_vars = exprs(COUNTRY = country_code)
#'   )
#' covar
#'
#' @rdname country_code_lookup
country_code_lookup <- tribble(
  ~country_code, ~country_name, ~country_number,
  "ABW", "Aruba", 1,
  "AFG", "Afghanistan", 2,
  "AGO", "Angola", 3,
  "AIA", "Anguilla", 4,
  "ALA", "Åland Islands", 5,
  "ALB", "Albania", 6,
  "AND", "Andorra", 7,
  "ARE", "United Arab Emirates", 8,
  "ARG", "Argentina", 9,
  "ARM", "Armenia", 10,
  "ASM", "American Samoa", 11,
  "ATA", "Antarctica", 12,
  "ATF", "French Southern Territories", 13,
  "ATG", "Antigua and Barbuda", 14,
  "AUS", "Australia", 15,
  "AUT", "Austria", 16,
  "AZE", "Azerbaijan", 17,
  "BDI", "Burundi", 18,
  "BEL", "Belgium", 19,
  "BEN", "Benin", 20,
  "BES", "Bonaire, Sint Eustatius and Saba", 21,
  "BFA", "Burkina Faso", 22,
  "BGD", "Bangladesh", 23,
  "BGR", "Bulgaria", 24,
  "BHR", "Bahrain", 25,
  "BHS", "Bahamas", 26,
  "BIH", "Bosnia and Herzegovina", 27,
  "BLM", "Saint Barthélemy", 28,
  "BLR", "Belarus", 29,
  "BLZ", "Belize", 30,
  "BMU", "Bermuda", 31,
  "BOL", "Bolivia, Plurinational State of", 32,
  "BRA", "Brazil", 33,
  "BRB", "Barbados", 34,
  "BRN", "Brunei Darussalam", 35,
  "BTN", "Bhutan", 36,
  "BVT", "Bouvet Island", 37,
  "BWA", "Botswana", 38,
  "CAF", "Central African Republic", 39,
  "CAN", "Canada", 40,
  "CCK", "Cocos (Keeling) Islands", 41,
  "CHE", "Switzerland", 42,
  "CHL", "Chile", 43,
  "CHN", "China", 44,
  "CIV", "Côte d'Ivoire", 45,
  "CMR", "Cameroon", 46,
  "COD", "Congo, Democratic Republic of the", 47,
  "COG", "Congo", 48,
  "COK", "Cook Islands", 49,
  "COL", "Colombia", 50,
  "COM", "Comoros", 51,
  "CPV", "Cabo Verde", 52,
  "CRI", "Costa Rica", 53,
  "CUB", "Cuba", 54,
  "CUW", "Curaçao", 55,
  "CXR", "Christmas Island", 56,
  "CYM", "Cayman Islands", 57,
  "CYP", "Cyprus", 58,
  "CZE", "Czechia", 59,
  "DEU", "Germany", 60,
  "DJI", "Djibouti", 61,
  "DMA", "Dominica", 62,
  "DNK", "Denmark", 63,
  "DOM", "Dominican Republic", 64,
  "DZA", "Algeria", 65,
  "ECU", "Ecuador", 66,
  "EGY", "Egypt", 67,
  "ERI", "Eritrea", 68,
  "ESH", "Western Sahara", 69,
  "ESP", "Spain", 70,
  "EST", "Estonia", 71,
  "ETH", "Ethiopia", 72,
  "FIN", "Finland", 73,
  "FJI", "Fiji", 74,
  "FLK", "Falkland Islands (Malvinas)", 75,
  "FRA", "France", 76,
  "FRO", "Faroe Islands", 77,
  "FSM", "Micronesia, Federated States of", 78,
  "GAB", "Gabon", 79,
  "GBR", "United Kingdom of Great Britain and Northern Ireland", 80,
  "GEO", "Georgia", 81,
  "GGY", "Guernsey", 82,
  "GHA", "Ghana", 83,
  "GIB", "Gibraltar", 84,
  "GIN", "Guinea", 85,
  "GLP", "Guadeloupe", 86,
  "GMB", "Gambia", 87,
  "GNB", "Guinea-Bissau", 88,
  "GNQ", "Equatorial Guinea", 89,
  "GRC", "Greece", 90,
  "GRD", "Grenada", 91,
  "GRL", "Greenland", 92,
  "GTM", "Guatemala", 93,
  "GUF", "French Guiana", 94,
  "GUM", "Guam", 95,
  "GUY", "Guyana", 96,
  "HKG", "Hong Kong", 97,
  "HMD", "Heard Island and McDonald Islands", 98,
  "HND", "Honduras", 99,
  "HRV", "Croatia", 100,
  "HTI", "Haiti", 101,
  "HUN", "Hungary", 102,
  "IDN", "Indonesia", 103,
  "IMN", "Isle of Man", 104,
  "IND", "India", 105,
  "IOT", "British Indian Ocean Territory", 106,
  "IRL", "Ireland", 107,
  "IRN", "Iran, Islamic Republic of", 108,
  "IRQ", "Iraq", 109,
  "ISL", "Iceland", 110,
  "ISR", "Israel", 111,
  "ITA", "Italy", 112,
  "JAM", "Jamaica", 113,
  "JEY", "Jersey", 114,
  "JOR", "Jordan", 115,
  "JPN", "Japan", 116,
  "KAZ", "Kazakhstan", 117,
  "KEN", "Kenya", 118,
  "KGZ", "Kyrgyzstan", 119,
  "KHM", "Cambodia", 120,
  "KIR", "Kiribati", 121,
  "KNA", "Saint Kitts and Nevis", 122,
  "KOR", "Korea, Republic of", 123,
  "KWT", "Kuwait", 124,
  "LAO", "Lao People's Democratic Republic", 125,
  "LBN", "Lebanon", 126,
  "LBR", "Liberia", 127,
  "LBY", "Libya", 128,
  "LCA", "Saint Lucia", 129,
  "LIE", "Liechtenstein", 130,
  "LKA", "Sri Lanka", 131,
  "LSO", "Lesotho", 132,
  "LTU", "Lithuania", 133,
  "LUX", "Luxembourg", 134,
  "LVA", "Latvia", 135,
  "MAC", "Macao", 136,
  "MAF", "Saint Martin (French part)", 137,
  "MAR", "Morocco", 138,
  "MCO", "Monaco", 139,
  "MDA", "Moldova, Republic of", 140,
  "MDG", "Madagascar", 141,
  "MDV", "Maldives", 142,
  "MEX", "Mexico", 143,
  "MHL", "Marshall Islands", 144,
  "MKD", "North Macedonia", 145,
  "MLI", "Mali", 146,
  "MLT", "Malta", 147,
  "MMR", "Myanmar", 148,
  "MNE", "Montenegro", 149,
  "MNG", "Mongolia", 150,
  "MNP", "Northern Mariana Islands", 151,
  "MOZ", "Mozambique", 152,
  "MRT", "Mauritania", 153,
  "MSR", "Montserrat", 154,
  "MTQ", "Martinique", 155,
  "MUS", "Mauritius", 156,
  "MWI", "Malawi", 157,
  "MYS", "Malaysia", 158,
  "MYT", "Mayotte", 159,
  "NAM", "Namibia", 160,
  "NCL", "New Caledonia", 161,
  "NER", "Niger", 162,
  "NFK", "Norfolk Island", 163,
  "NGA", "Nigeria", 164,
  "NIC", "Nicaragua", 165,
  "NIU", "Niue", 166,
  "NLD", "Netherlands, Kingdom of the", 167,
  "NOR", "Norway", 168,
  "NPL", "Nepal", 169,
  "NRU", "Nauru", 170,
  "NZL", "New Zealand", 171,
  "OMN", "Oman", 172,
  "PAK", "Pakistan", 173,
  "PAN", "Panama", 174,
  "PCN", "Pitcairn", 175,
  "PER", "Peru", 176,
  "PHL", "Philippines", 177,
  "PLW", "Palau", 178,
  "PNG", "Papua New Guinea", 179,
  "POL", "Poland", 180,
  "PRI", "Puerto Rico", 181,
  "PRK", "Korea, Democratic People's Republic of", 182,
  "PRT", "Portugal", 183,
  "PRY", "Paraguay", 184,
  "PSE", "Palestine, State of", 185,
  "PYF", "French Polynesia", 186,
  "QAT", "Qatar", 187,
  "REU", "Réunion", 188,
  "ROU", "Romania", 189,
  "RUS", "Russian Federation", 190,
  "RWA", "Rwanda", 191,
  "SAU", "Saudi Arabia", 192,
  "SDN", "Sudan", 193,
  "SEN", "Senegal", 194,
  "SGP", "Singapore", 195,
  "SGS", "South Georgia and the South Sandwich Islands", 196,
  "SHN", "Saint Helena, Ascension and Tristan da Cunha", 197,
  "SJM", "Svalbard and Jan Mayen", 198,
  "SLB", "Solomon Islands", 199,
  "SLE", "Sierra Leone", 200,
  "SLV", "El Salvador", 201,
  "SMR", "San Marino", 202,
  "SOM", "Somalia", 203,
  "SPM", "Saint Pierre and Miquelon", 204,
  "SRB", "Serbia", 205,
  "SSD", "South Sudan", 206,
  "STP", "Sao Tome and Principe", 207,
  "SUR", "Suriname", 208,
  "SVK", "Slovakia", 209,
  "SVN", "Slovenia", 210,
  "SWE", "Sweden", 211,
  "SWZ", "Eswatini", 212,
  "SXM", "Sint Maarten (Dutch part)", 213,
  "SYC", "Seychelles", 214,
  "SYR", "Syrian Arab Republic", 215,
  "TCA", "Turks and Caicos Islands", 216,
  "TCD", "Chad", 217,
  "TGO", "Togo", 218,
  "THA", "Thailand", 219,
  "TJK", "Tajikistan", 220,
  "TKL", "Tokelau", 221,
  "TKM", "Turkmenistan", 222,
  "TLS", "Timor-Leste", 223,
  "TON", "Tonga", 224,
  "TTO", "Trinidad and Tobago", 225,
  "TUN", "Tunisia", 226,
  "TUR", "Turkey", 227,
  "TUV", "Tuvalu", 228,
  "TWN", "Taiwan, Province of China", 229,
  "TZA", "Tanzania, United Republic of", 230,
  "UGA", "Uganda", 231,
  "UKR", "Ukraine", 232,
  "UMI", "United States Minor Outlying Islands", 233,
  "URY", "Uruguay", 234,
  "USA", "United States of America", 235,
  "UZB", "Uzbekistan", 236,
  "VAT", "Holy See", 237,
  "VCT", "Saint Vincent and the Grenadines", 238,
  "VEN", "Venezuela, Bolivarian Republic of", 239,
  "VGB", "Virgin Islands (British)", 240,
  "VIR", "Virgin Islands (U.S.)", 241,
  "VNM", "Viet Nam", 242,
  "VUT", "Vanuatu", 243,
  "WLF", "Wallis and Futuna", 244,
  "WSM", "Samoa", 245,
  "YEM", "Yemen", 246,
  "ZAF", "South Africa", 247,
  "ZMB", "Zambia", 248,
  "ZWE", "Zimbabwe", 249
)
