name: Create the AGENTS.md

on:
  push:
    branches:
      - 2920-add-copilot-instructions
    paths:
      - '.github/workflows/sync-admiralci-agents.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

jobs:
  create-agents-md:
    permissions:
      contents: write
      pull-requests: write
    uses: pharmaverse/admiralci/.github/workflows/create-agents-md.yml@231-add-workflow-to-create-ai-agentmd-files
    with:
      package_name: admiral
      target_branch: 2920-add-copilot-instructions