# Source:  pilot5, Eli Miller, @ July 15, 2025, modified
# Changes made with assistance of gemini LLM.

name: Verify Templates ✅

on:
  pull_request:
    branches:
      -  main
    paths:
      -  '**.yml'
# force ?  github actions to "see" this yml file
  push:
    branches:
      -  verify_version3    # push to this branch

run-name: PR Build for ${{ github.event.pull_request.number }} by @${{ github.actor }}

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Set US Eastern timezone
        run: sudo timedatectl set-timezone America/New_York

      - name: Check out repository
        uses: actions/checkout@v4
        with:
         ref: ${{ github.event.pull_request.head.ref }} # Checkout the branch of the PR
         fetch-depth: 0

      - name: Print PR details
        run: |
          echo "This workflow is running for PR # ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Last commit SHA: ${{ github.sha }}"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "jsonlite", "quarto", "diffdf", "rmarkdown", "safetyData", "tibble", "stringr"), repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'

      - name: Run QC script
        run: R -e 'quarto::quarto_render("qcReport.qmd")'

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: qcReport.html
          path: qcReport.html

      - name: Comment PR with qc.Rmd (if Pull Request)
        # This step will only run if the event is a pull_request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: qc.Rmd
          comment-tag: qc-dataset
        # Dynamically get the PR number for the current pull request
          pr-number: ${{ github.event.pull_request.number }}

      - name: Log qc.Rmd content (if Push or Workflow Dispatch)
        # This step will run for push or workflow_dispatch events
        # It logs the content to the workflow run output
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo "--- Content of qc.Rmd ---"
          cat qc.Rmd
          echo "-------------------------"


#      - name: Fail Step if no differences found
#        if: hashFiles('qc.fail') != ''
#        uses: actions/github-script@v3
#        with:
#          script: |
#            core.setFailed('QC Check failed!')

