name:  verify_templates_experimental

run-name: EXPERIMENTAL

# To establish `workflow_dispatch` must use `default` branch.
# this yaml workflow runs when a push occurs on this branch
# OR, manually,

on:
  push:
    branches:  [2642_verify_templates_results]
  workflow_dispatch:
  pull_request:

jobs:
  verify_templates:
    runs-on: ubuntu-latest
    env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Checkout repo
        uses: actions/checkout@v4

# missing devtools::
      - uses: r-lib/actions/setup-r-dependencies@v2

# copy from 
#      - Install Dependencies from DESCRIPTION 
#        run |
#          install.packages(c("remotes", "devtools"))
#          remotes::install_local(force = TRUE, dependencies = TRUE)
#        shell: Rscript {0}
# env:
# R_REMOTES_STANDALONE: "true"

# WHY do next 2 lines = SYNTAX error?
#......- name: needed packages
#        run:  Rscript -e 'install.packages(c("devtools", "diffdf"))'


      - name: source
        run:  Rscript -e 'install.packages(c("devtools")); source("data-raw/admiral_verify_templates.R")'


      - name: run the code
        run:  Rscript -e 'load_all(); verify_templates()'

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
