# WORKS
name:  verify_templates_experimental

run-name: EXPERIMENTAL


on:
  workflow_dispatch:
    branches: 2642_verify_templates_results 

jobs:
  task1:
    runs-on: ubuntu-latest
    if: ${{ gitub.event_name == 'workflow_dispatch' }}
    steps:
      - name: echo
        run:  echo "This is workflow_dispatch"

       
  print_results:
    runs-on: ubuntu-latest

    env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: load_all
      	run: Rscript -e 'devtools::load_all()'

      - name: source 
        run:  Rscript -e 'source("data-raw/admiral_verify_templates.R")'
       
      - name: run the code
	run:  Rscript -e 'verify_templates()'

